.catalog:
  name: "Percona XtraDB Cluster Ronin"
  version: 5.6.28-rancher1
  description: |
    Percona XtraDB Cluster 5.6.28
  questions:
    - variable: "boostra_host_name"
      type: string
      required: false
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
      default: "asd"
members:
  scale: 3