.catalog:
  name: "Percona XtraDB Cluster Ronin"
  version: 5.6.28-rancher1
  description: |
    Percona XtraDB Cluster 5.6.28
  questions:
    - variable: "mysql_root_password"
      type: string
      required: false
      label: "MySQL Root Password"
      description: "Password given to the root mysql user"
      default: "asd"
    - variable: "pxc_sst_password"
      type: string
      required: false
      label: "PXC SST Password"
      description: "Password given to the sst mysql user"   
      default: ""   
    - variable: "mysql_database"
      type: string
      required: false
      label: "MySQL Database Name"
      description: "MySQL database to create"
      default: "necdb"
    - variable: "mysql_user"
      type: string
      required: false
      description: "MySQL user for the created database"
      label: "MySQL DB User"
      default: "user"
    - variable: "mysql_password"
      type: string
      required: false
      label: "MySQL DB Password"
      default: "asd"
      description: "Password for the MySQL user of the created database"
members:
  scale: 3